# Generated by Django 5.0.4 on 2024-04-23 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_members_remove_friends_name_friends_members_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='description',
            field=models.TextField(default='.'),
        ),
    ]
