# Generated by Django 5.0.4 on 2024-04-24 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_nickname_profile_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='text',
            field=models.TextField(default='.'),
        ),
    ]
