# Generated by Django 5.0.4 on 2024-04-24 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_comments_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='ava_url',
        ),
    ]
