# Generated by Django 5.0.4 on 2024-04-24 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_profile_ava_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friends',
            name='members',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='friends', to='api.members'),
        ),
        migrations.AlterField(
            model_name='friends',
            name='nickname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend', to='api.members'),
        ),
    ]
